/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IReputation,
  IReputationInterface,
} from "../../../lib/interfaces/IReputation";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_userCredit",
        type: "uint256",
      },
    ],
    name: "limiter",
    outputs: [
      {
        internalType: "uint256",
        name: "_spendLimit",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class IReputation__factory {
  static readonly abi = _abi;
  static createInterface(): IReputationInterface {
    return new utils.Interface(_abi) as IReputationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IReputation {
    return new Contract(address, _abi, signerOrProvider) as IReputation;
  }
}
