/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface ReputationInterface extends utils.Interface {
  functions: {
    "limiter(uint256)": FunctionFragment;
    "magicValue()": FunctionFragment;
    "maxLimit()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "limiter" | "magicValue" | "maxLimit"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "limiter",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "magicValue",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "maxLimit", values?: undefined): string;

  decodeFunctionResult(functionFragment: "limiter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "magicValue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxLimit", data: BytesLike): Result;

  events: {};
}

export interface Reputation extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ReputationInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    limiter(
      _userCredit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _spendLimit: BigNumber }>;

    magicValue(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxLimit(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  limiter(
    _userCredit: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  magicValue(overrides?: CallOverrides): Promise<BigNumber>;

  maxLimit(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    limiter(
      _userCredit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    magicValue(overrides?: CallOverrides): Promise<BigNumber>;

    maxLimit(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    limiter(
      _userCredit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    magicValue(overrides?: CallOverrides): Promise<BigNumber>;

    maxLimit(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    limiter(
      _userCredit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    magicValue(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxLimit(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
