export enum P2PixErrors {
  OnlySeller = "OnlySeller",
  NotExpired = "NotExpired",
  LoopOverflow = "LoopOverflow",
  InvalidDeposit = "InvalidDeposit",
  NotEnoughTokens = "NotEnoughTokens",
  AlreadyReleased = "AlreadyReleased",
  TxAlreadyUsed = "TxAlreadyUsed",
  InvalidSigner = "InvalidSigner",
  Unauthorized = "Unauthorized",
  TokenDenied = "TokenDenied",
  NoTokens = "NoTokens",
  LengthMismatch = "LengthMismatch",
  AddressDenied = "AddressDenied",
  AmountNotAllowed = "AmountNotAllowed",
  LockExpired = "LockExpired",
  EmptyPixTarget = "EmptyPixTarget",
  MaxBalExceeded = "MaxBalExceeded",
  NotInitialized = "NotInitialized",
  DecOverflow = "DecOverflow",
  CallFailed = "CallFailed",
}
