export enum P2PixErrors {
  DepositAlreadyExists = "DepositAlreadyExists",
  OnlySeller = "OnlySeller",
  NotExpired = "NotExpired",
  LoopOverflow = "LoopOverflow",
  InvalidDeposit = "InvalidDeposit",
  NotEnoughTokens = "NotEnoughTokens",
  AlreadyReleased = "AlreadyReleased",
  TxAlreadyUsed = "TxAlreadyUsed",
  InvalidSigner = "InvalidSigner",
  UNAUTHORIZED = "UNAUTHORIZED",
  TokenDenied = "TokenDenied",
  NoTokens = "NoTokens",
  LengthMismatch = "LengthMismatch",
  AddressDenied = "AddressDenied",
  AmountNotAllowed = "AmountNotAllowed",
  LockExpired = "LockExpired",
}
