/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type { Counters, CountersInterface } from "../../../lib/utils/Counters";

const _abi = [
  {
    inputs: [],
    name: "DecOverflow",
    type: "error",
  },
];

const _bytecode =
  "0x602d6037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea164736f6c6343000809000a";

type CountersConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CountersConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Counters__factory extends ContractFactory {
  constructor(...args: CountersConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Counters> {
    return super.deploy(overrides || {}) as Promise<Counters>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Counters {
    return super.attach(address) as Counters;
  }
  override connect(signer: Signer): Counters__factory {
    return super.connect(signer) as Counters__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CountersInterface {
    return new utils.Interface(_abi) as CountersInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Counters {
    return new Contract(address, _abi, signerOrProvider) as Counters;
  }
}
